name: Generate Snake Contribution Graph

on:
  schedule: # akan berjalan otomatis setiap hari
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: nauvalathalla
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg

      - name: Push the generated SVG to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution snake"
          add: "github-contribution-grid-snake*.svg"
